---
name: media-docker
description: all-in-one deployment and configuration for an all-in-one media server.
url: https://media-docker.com
repository: https://github.com/keerio/media-docker
twitter:
  username: none
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
exclude:
- .gitignore
- .gitattributes
- CNAME
- .travis.yml
- logo.psd
